package cn.jblog.common.model;

import cn.jblog.common.model.base.BaseArtStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArtStat extends BaseArtStat<ArtStat> {
	public static final ArtStat dao = new ArtStat().dao();
}
