package cn.jblog.common.model;

import cn.jblog.common.model.base.BaseArtType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArtType extends BaseArtType<ArtType> {
	public static final ArtType dao = new ArtType().dao();
}
