package cn.jblog.common.model;

import cn.jblog.common.model.base.BaseSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConfig extends BaseSysConfig<SysConfig> {
	public static final SysConfig dao = new SysConfig().dao();
}
