package cn.jblog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArtStat<M extends BaseArtStat<M>> extends Model<M> implements IBean {

	public M setTid(java.lang.Integer tid) {
		set("tid", tid);
		return (M)this;
	}

	public java.lang.Integer getTid() {
		return get("tid");
	}

	public M setReadCount(java.lang.Integer readCount) {
		set("read_count", readCount);
		return (M)this;
	}

	public java.lang.Integer getReadCount() {
		return get("read_count");
	}

	public M setGoodCount(java.lang.Integer goodCount) {
		set("good_count", goodCount);
		return (M)this;
	}

	public java.lang.Integer getGoodCount() {
		return get("good_count");
	}

}
