package cn.jblog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public M setUserPassword(java.lang.String userPassword) {
		set("user_password", userPassword);
		return (M)this;
	}

	public java.lang.String getUserPassword() {
		return get("user_password");
	}

	public M setUserImage(java.lang.String userImage) {
		set("user_image", userImage);
		return (M)this;
	}

	public java.lang.String getUserImage() {
		return get("user_image");
	}

	public M setRegTime(java.util.Date regTime) {
		set("reg_time", regTime);
		return (M)this;
	}

	public java.util.Date getRegTime() {
		return get("reg_time");
	}

}
