package cn.jblog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setTid(java.lang.Integer tid) {
		set("tid", tid);
		return (M)this;
	}

	public java.lang.Integer getTid() {
		return get("tid");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setLoadUrl(java.lang.String loadUrl) {
		set("load_url", loadUrl);
		return (M)this;
	}

	public java.lang.String getLoadUrl() {
		return get("load_url");
	}

	public M setLable(java.lang.String lable) {
		set("lable", lable);
		return (M)this;
	}

	public java.lang.String getLable() {
		return get("lable");
	}

	public M setKeyWord(java.lang.String keyWord) {
		set("key_word", keyWord);
		return (M)this;
	}

	public java.lang.String getKeyWord() {
		return get("key_word");
	}

	public M setDecoration(java.lang.String decoration) {
		set("decoration", decoration);
		return (M)this;
	}

	public java.lang.String getDecoration() {
		return get("decoration");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setAlterTime(java.util.Date alterTime) {
		set("alter_time", alterTime);
		return (M)this;
	}

	public java.util.Date getAlterTime() {
		return get("alter_time");
	}

	public M setIsTop(java.lang.Integer isTop) {
		set("is_top", isTop);
		return (M)this;
	}

	public java.lang.Integer getIsTop() {
		return get("is_top");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
